### ISSUE TITLE
Escolher apenas um idioma para o código.

### ISSUE THREAD

**Issue by natan-xav2019** [IsabelleNFerreira/SnakeGame#1]
Acredito que uma boa pratica de programação.

Programar em apenas um idioma de preferencia sempre o inglês.

Uma boa dica e dar `ctrl + D` e selecionar todas as variáveis no vs-code e alterar todas de uma vez.

**Comment by IsabelleNFerreira** [comment]
Agradeço pela sugestão e a dica, Natan!
Feedbacks são sempre importantes.
